///|
/// `fit` scales and translates a `Path` so that it fits within
/// the provided Rectangle at the given `anchor` point. If `fill`
/// is true, then the `anchor` point is ignored and the path's
/// aspect ratio is ignored, meaning that the path will be scaled
/// independently along the X and Y axes to fix completely within
/// the rectangle.
// pub fn fit(
//   self : Path,
//   r : Rectangle,
//   anchor : Anchor,
//   y_up~ : Bool = false,
//   fill~ : Bool = false
// ) -> Unit {
//   ...
// }
